In [2]:
import pandas as pd
import os

In [3]:
os.getcwd()

'c:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\utils'

In [4]:
import glob
import pandas as pd

path = r'C:\Users\guill\Documents\1Repos\algoritmos-nlp\notebooks\resultados\notas\*.csv'
files = glob.glob(path)

files

['C:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\resultados\\notas\\2023-05-27_09-48-25_metadata.csv',
 'C:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\resultados\\notas\\2023-05-27_10-45-07_metadata.csv',
 'C:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\resultados\\notas\\2023-05-27_18-01-23_metadata.csv',
 'C:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\resultados\\notas\\2023-05-28_00-15-11_metadata.csv',
 'C:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\resultados\\notas\\2023-05-28_11-45-57_metadata.csv',
 'C:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\resultados\\notas\\2023-05-28_12-13-34_metadata.csv',
 'C:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\resultados\\notas\\2023-05-28_15-44-00_metadata.csv',
 'C:\\Users\\guill\\Documents\\1Repos\\algoritmos-nlp\\notebooks\\resultados\\notas\\2023-05-28_19-27-55_metadata.csv']

In [5]:
df_list = []
for file in files:
    df = pd.read_csv(file, sep=",", engine="c", on_bad_lines='skip')
    df_list.append(df)

all_data = pd.concat(df_list, axis=0, ignore_index=True)
all_data

,BATCH_SIZE,EPOCHS,LEARNING_RATE,PRE_TRAINED_MODEL_NAME,tipo,idioma,train_acc,val_acc,tiempo_seg,SISTEMA
0,16,5,0.00001,dccuchile/bert-base-spanish-wwm-cased,AMAZON,es,0.790648,0.630000,24668.000000,PYTHON
1,32,4,0.00003,google/bert_uncased_L-4_H-256_A-4,AGNEWS,en,0.940396,0.912632,1180.000000,PYTHON
2,32,4,0.00003,small_bert_L4_256,AGNEWS,en,0.845659,0.841347,812.999989,SPARK
3,16,2,0.00001,bert_base_cased,AMAZON,es,0.545230,0.554852,2460.814968,SPARK
4,16,2,0.00001,bert_base_cased,AMAZON,es,0.549966,0.558520,1854.595443,NaN
5,32,4,0.00003,small_bert_L4_256,AGNEWS,en,0.845057,0.841616,274.250393,NaN
6,32,4,0.00003,small_bert_L4_256,AGNEWS,en,0.845028,0.841481,272.546843,NaN
7,16,2,0.00001,dccuchile/bert-base-spanish-wwm-cased,AMAZON,es,0.677111,0.650667,9995.952731,NaN

In [6]:
from datetime import timedelta



# Convertir la columna Time en formato h.m.s
all_data['runtime_hms'] = all_data['tiempo_seg'].apply(lambda x: str(timedelta(seconds=x)))

# datos de AGNEWS

In [7]:
all_data.query("tipo=='AGNEWS'")[['PRE_TRAINED_MODEL_NAME','tipo','train_acc','val_acc','runtime_hms']]

,PRE_TRAINED_MODEL_NAME,tipo,train_acc,val_acc,runtime_hms
1,google/bert_uncased_L-4_H-256_A-4,AGNEWS,0.940396,0.912632,0:19:40
2,small_bert_L4_256,AGNEWS,0.845659,0.841347,0:13:32.999989
5,small_bert_L4_256,AGNEWS,0.845057,0.841616,0:04:34.250393
6,small_bert_L4_256,AGNEWS,0.845028,0.841481,0:04:32.546843

# datos amazon

In [9]:
all_data.query("tipo=='AMAZON'")[['PRE_TRAINED_MODEL_NAME','tipo','train_acc','val_acc','runtime_hms']]

,PRE_TRAINED_MODEL_NAME,tipo,train_acc,val_acc,runtime_hms
0,dccuchile/bert-base-spanish-wwm-cased,AMAZON,0.790648,0.630000,6:51:08
3,bert_base_cased,AMAZON,0.545230,0.554852,0:41:00.814968
4,bert_base_cased,AMAZON,0.549966,0.558520,0:30:54.595443
7,dccuchile/bert-base-spanish-wwm-cased,AMAZON,0.677111,0.650667,2:46:35.952731